### ISSUE TITLE
Release 2.0 doesn't compile on visual studio 2013

### ISSUE THREAD

**Issue by mgrandi** [tghosgor/threadpool11#6] opened 2014-01-31 23:52 UTC
I know that CMake doesn't have 'official' support for visual studio 2013, so i generated files for Visual Studio 2012, and then just opened it with 13, and made sure that its using the latest 'toolkit' in the project properties, but when i try to compile the project ALL_BUILD, it doesn't compile.

```
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
2>------ Build started: Project: threadpool11, Configuration: Debug Win32 ------
2>  Pool.cpp
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(126): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(144): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(154): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(162): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(183): error C2228: left of '.load' must have class/struct/union
2>src\Pool.cpp(44): error C2228: left of '.load' must have class/struct/union
2>src\Pool.cpp(50): error C2511: 'void threadpool11::Pool::setWorkerCount(const size_t &,const threadpool11::Pool::Method &)' : overloaded member function not found in 'threadpool11::Pool'
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(53) : see declaration of 'threadpool11::Pool'
2>src\Pool.cpp(51): error C2352: 'threadpool11::Pool::getWorkerCount' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(126) : see declaration of 'threadpool11::Pool::getWorkerCount'
2>src\Pool.cpp(52): error C2352: 'threadpool11::Pool::getWorkerCount' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(126) : see declaration of 'threadpool11::Pool::getWorkerCount'
2>src\Pool.cpp(54): error C2352: 'threadpool11::Pool::getWorkerCount' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(126) : see declaration of 'threadpool11::Pool::getWorkerCount'
2>src\Pool.cpp(57): error C2228: left of '.load' must have class/struct/union
2>src\Pool.cpp(63): error C2511: 'void threadpool11::Pool::incWorkerCountBy(const size_t &)' : overloaded member function not found in 'threadpool11::Pool'
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(53) : see declaration of 'threadpool11::Pool'
2>src\Pool.cpp(64): error C2352: 'threadpool11::Pool::spawnWorkers' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(78) : see declaration of 'threadpool11::Pool::spawnWorkers'
2>src\Pool.cpp(68): error C2511: 'void threadpool11::Pool::decWorkerCountBy(size_t,const threadpool11::Pool::Method &)' : overloaded member function not found in 'threadpool11::Pool'
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(53) : see declaration of 'threadpool11::Pool'
2>src\Pool.cpp(69): error C2352: 'threadpool11::Pool::getWorkerCount' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(126) : see declaration of 'threadpool11::Pool::getWorkerCount'
2>src\Pool.cpp(69): error C2780: '_Ty std::min(std::initializer_list<_Elem>,_Pr)' : expects 2 arguments - 1 provided
2>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4141) : see declaration of 'std::min'
2>src\Pool.cpp(69): error C2780: 'const _Ty &std::min(const _Ty &,const _Ty &,_Pr)' : expects 3 arguments - 1 provided
2>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4134) : see declaration of 'std::min'
2>src\Pool.cpp(69): error C2784: '_Ty std::min(std::initializer_list<_Elem>)' : could not deduce template argument for 'std::initializer_list<_Elem>' from 'size_t'
2>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4125) : see declaration of 'std::min'
2>src\Pool.cpp(69): error C2780: 'const _Ty &std::min(const _Ty &,const _Ty &)' : expects 2 arguments - 1 provided
2>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4119) : see declaration of 'std::min'
2>src\Pool.cpp(75): error C2352: 'threadpool11::Pool::postWork' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(212) : see declaration of 'threadpool11::Pool::postWork'
2>src\Pool.cpp(82): error C2352: 'threadpool11::Pool::postWork' : illegal call of non-static member function
2>          C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(212) : see declaration of 'threadpool11::Pool::postWork'
2>  Worker.cpp
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(126): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(144): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(154): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(162): error C2228: left of '.load' must have class/struct/union
2>C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0\threadpool11\include\threadpool11/Pool.h(183): error C2228: left of '.load' must have class/struct/union
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by tghosgor** [comment] 2014-02-01 01:56
This MSVC is a pain.

Apparently decltype(member_variable.method()) is a GNU ext. or MSVC just does not support it.
Pushed the fix to 2.0 branch and tagged 2.0.1.

There is huge speed difference between Debug and Release versions by the way.

**Closed as completed by tghosgor** 2014-02-01 01:56 UTC
Labels: bug

**Comment by Darelbi** [comment] 2014-02-01 11:59
Hi, Visual studio still does not support C++11  at 100%, most of code that compiles fine with Clang or GCC still does not compile on visual studio (they have to implement C++11 features also in debugger and code completion and that's not easy)

**Comment by tghosgor** [comment] 2014-02-01 12:06
Sorry wrong link. Removed previous answer. Here is new:

Yeah unfortunately it does not.

Current `2.0.1` compiles on my fully updated MSVC. Try updating it.

My `cl` prints `version 18.00.21005.1 for x86`.

**Comment by mgrandi** [comment] 2014-02-04 19:39
I believe i am running the latest version of visual studio and its compiler, its the same version as the one you are running...

```
C:\Users\mgrandi\Desktop\threadpool11-2.0.0\threadpool11-2.0.0>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe"
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.21005.1 for x86
```

And i know there is a difference between release and debug, but its obviously not building . Maybe it has something to do with the fact that i used CMake to generate the visual studio project files?

**Comment by tghosgor** [comment] 2014-02-04 19:44
I use CMake too. I reproduced the exact errors and fixed it. Are you sure you pulled [the commit that fixes the issue](https://github.com/metherealone/threadpool11/commit/5e7bc305a2c7196a33da6af78025e91346108e5d)?

**Comment by mgrandi** [comment] 2014-02-04 19:55
I updated and that indeed fixes the issue, thanks. Although I might not be using this library after all, as I thought it just needed one boost file, but i guess to use that one file you have to include pretty much all of boost, which is a large requirement when you don't already use boost, but that is for another thread. Thanks again =)

**Comment by tghosgor** [comment] 2014-02-04 20:02
Nothing in boost is a single file since boost heavily uses abstraction on almost everything internally because boost was pretty much the same as C++11 when there was no C++11. I assume inclusions are mostly thin wrappers for C++11 compilers now, but also support pre-C++11. The actual code which is being used aside from abstraction is indeed a single file. It is no reason to not use something, boost is well written and fast but suit yourself. :)
